TOP=..
include $(TOP)/mk/base.mk

PROG=mount_lasagna_helper
SRCS=mount_lasagna_helper.c
CXXLINK=no

INST=mount_lasagna_helper
INSTFLAGS=
INSTDIR=$(ROOTPREFIX)/sbin

include $(TOP)/mk/prog.mk
include $(TOP)/mk/install.mk
