TOP=..
include $(TOP)/mk/base.mk

LIB=pqlutil
SRCS=	compile.c interact.c printdumps.c printtrace.c printerrors.c tdb.c \
	pqlpickle.c

CFLAGS+=-I$(TOP)/include

include $(TOP)/mk/lib.mk
include $(TOP)/mk/noinstall.mk
