TOP=..
include $(TOP)/mk/base.mk

PROG=umount_lasagna_helper
SRCS=umount_lasagna_helper.c
CXXLINK=no

INST=umount_lasagna_helper
INSTFLAGS=
INSTDIR=$(ROOTPREFIX)/sbin

include $(TOP)/mk/prog.mk
include $(TOP)/mk/install.mk
